CREATE TABLE authors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(200) NOT NULL,
    second_name VARCHAR(200) NOT NULL,
    description TEXT
);

CREATE TABLE books (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(500) NOT NULL,
    description TEXT,
    author_id   BIGINT       NOT NULL REFERENCES authors (id)
);

-- The books panel always filters by author, and authors are listed alphabetically.
CREATE INDEX idx_books_author_id ON books (author_id);
CREATE INDEX idx_authors_name ON authors (second_name, first_name);
